### ISSUE TITLE
Does not work with DaftMonk Angular Full Stack - angular-bs-confirm.js:32 undefined on $element.tooltip

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [hash-bang/angular-bs-confirm#1]
Not sure what is going on or where the .tooltip should be defined in.

On install: Note the invalid-meta
bower not-cached    git://github.com/hash-bang/angular-bs-confirm.git#*
bower resolve       git://github.com/hash-bang/angular-bs-confirm.git#*
bower checkout      angular-bs-confirm#master
bower invalid-meta  angular-bs-confirm is missing "ignore" entry in bower.json
bower resolved      git://github.com/hash-bang/angular-bs-confirm.git#0cde4a8096
bower cached        git://github.com/twbs/bootstrap.git#3.3.5
bower validate      3.3.5 against git://github.com/twbs/bootstrap.git#~3.3.5

I also tried installing the full version of JQuery to see if that would help but it didnt.

If it want you can view my project here: https://github.com/MichaelLeeHobbs/freeTheVote
I was attempting to use angular-bs-confirm on vote view for the delete.

**Comment by hash-bang** [comment]
Thanks for the bug report.

Having a look at the linked project you don't appear to be using the `angular-bs-confirm` Bower module at all. Instead you seem to be using [angular-confirm](https://github.com/MrBoolean/ng-confirm).

Bower does have a tendency to annoy with its error messages but I've not had any other reports of it not being installable. Could you perhaps provide me with the branch of the repo you are trying to install this to or more error information so I can take a look?

**Comment by MichaelLeeHobbs** [comment]
Once angular-bs-confirm did not work I pruned it out and gave angular-ui-confirm a try which worked. Basically I was trying to use it on the delete button on the vote view.  

Line 32 in
https://github.com/MichaelLeeHobbs/freeTheVote/blob/master/client/app/vote/vote.html

**Comment by hash-bang** [comment]
I've tried to clone your project and boot it up but your Grunt config doesnt seem to run your frontend scripts though Babel (I'm guessing anyway).

There is an example of this directive in use, along with some of our other ones, at http://momsfriendlydevco.github.io/ng-mfdc if that helps.
